### ISSUE TITLE
Unable to display any content from the admin interface

### ISSUE THREAD

**Issue by pprw** [Daniel-KM/Omeka-S-module-Next#1]
After installing this module, I cannot anymore display any content from the admin interface.

Clicking on one item produces: 
```

Error
Call to undefined function Next\View\Helper\pmf()

Détails :

Error: Call to undefined function Next\View\Helper\pmf() in /sites/ehp-ahpnum/www/web_main/modules/Next/src/View/Helper/BrowsePreviousNext.php:122
Stack trace:
#0 /sites/ehp-ahpnum/www/web_main/modules/Next/src/View/Helper/BrowsePreviousNext.php(61): Next\View\Helper\BrowsePreviousNext->previousNext(Object(Omeka\Api\Representation\ItemRepresentation), Array)
#1 [internal function]: Next\View\Helper\BrowsePreviousNext->__invoke(Object(Omeka\Api\Representation\ItemRepresentation))
#2 /sites/ehp-ahpnum/www/web_main/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php(397): call_user_func_array(Object(Next\View\Helper\BrowsePreviousNext), Array)
#3 /sites/ehp-ahpnum/www/web_main/modules/Next/view/omeka/admin/item/show.phtml(28): Zend\View\Renderer\PhpRenderer->__call('browsePreviousN...', Array)
#4 /sites/ehp-ahpnum/www/web_main/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php(506): include('/sites/ehp-ahpn...')
#5 /sites/ehp-ahpnum/www/web_main/vendor/zendframework/zend-view/src/View.php(207): Zend\View\Renderer\PhpRenderer->render(NULL)
#6 /sites/ehp-ahpnum/www/web_main/vendor/zendframework/zend-view/src/View.php(236): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
#7 /sites/ehp-ahpnum/www/web_main/vendor/zendframework/zend-view/src/View.php(200): Zend\View\View->renderChildren(Object(Zend\View\Model\ViewModel))
#8 /sites/ehp-ahpnum/www/web_main/vendor/zendframework/zend-mvc/src/View/Http/DefaultRenderingStrategy.php(105): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
#9 /sites/ehp-ahpnum/www/web_main/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\View\Http\DefaultRenderingStrategy->render(Object(Zend\Mvc\MvcEvent))
#10 /sites/ehp-ahpnum/www/web_main/vendor/zendframework/zend-eventmanager/src/EventManager.php(171): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent))
#11 /sites/ehp-ahpnum/www/web_main/vendor/zendframework/zend-mvc/src/Application.php(367): Zend\EventManager\EventManager->triggerEvent(Object(Zend\Mvc\MvcEvent))
#12 /sites/ehp-ahpnum/www/web_main/vendor/zendframework/zend-mvc/src/Application.php(348): Zend\Mvc\Application->completeRequest(Object(Zend\Mvc\MvcEvent))
#13 /sites/ehp-ahpnum/www/web_main/index.php(21): Zend\Mvc\Application->run()
#14 {main}
```

**Comment by Daniel-KM** [comment]
Sorry, there was a bad commit. It is fixed (force) in the last commits and zip.
