### ISSUE TITLE
Next ver. 3.4.46

### ISSUE THREAD

**Issue by AngeloVenera** [Daniel-KM/Omeka-S-module-Next#10]
Hi at all,

When I click on "site administration" I get this response:

2023-05-15T09:36:39+00:00 ERR (3): Laminas\Form\Exception\InvalidElementException: No element by the name of [next_items_order_for_itemsets] found in form in /srv/http/omeka-s-4.0.1/vendor/laminas/laminas-form/src/Fieldset.php:207
Stack trace:
#0 /srv/http/omeka-s-4.0.1/modules/Next/Module.php(168): Laminas\Form\Fieldset->get()
#1 /srv/http/omeka-s-4.0.1/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Next\Module->handleSiteSettings()
#2 /srv/http/omeka-s-4.0.1/vendor/laminas/laminas-eventmanager/src/EventManager.php(171): Laminas\EventManager\EventManager->triggerListeners()
#3 /srv/http/omeka-s-4.0.1/application/src/Form/SiteSettingsForm.php(395): Laminas\EventManager\EventManager->triggerEvent()
#4 /srv/http/omeka-s-4.0.1/vendor/laminas/laminas-form/src/FormElementManager.php(233): Omeka\Form\SiteSettingsForm->init()
#5 /srv/http/omeka-s-4.0.1/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(630): Laminas\Form\FormElementManager->callElementInit()
#6 /srv/http/omeka-s-4.0.1/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(234): Laminas\ServiceManager\ServiceManager->doCreate()
#7 /srv/http/omeka-s-4.0.1/vendor/laminas/laminas-servicemanager/src/AbstractPluginManager.php(171): Laminas\ServiceManager\ServiceManager->get()
#8 /srv/http/omeka-s-4.0.1/vendor/laminas/laminas-form/src/FormElementManager.php(336): Laminas\ServiceManager\AbstractPluginManager->get()
#9 /srv/http/omeka-s-4.0.1/application/src/Mvc/Controller/Plugin/GetForm.php(33): Laminas\Form\FormElementManager->get()
#10 [internal function]: Omeka\Mvc\Controller\Plugin\GetForm->__invoke()
#11 /srv/http/omeka-s-4.0.1/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(275): call_user_func_array()
#12 /srv/http/omeka-s-4.0.1/application/src/Controller/SiteAdmin/IndexController.php(95): Laminas\Mvc\Controller\AbstractController->__call()
#13 /srv/http/omeka-s-4.0.1/vendor/laminas/laminas-mvc/src/Controller/AbstractActionController.php(71): Omeka\Controller\SiteAdmin\IndexController->editAction()
#14 /srv/http/omeka-s-4.0.1/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\Controller\AbstractActionController->onDispatch()
#15 /srv/http/omeka-s-4.0.1/vendor/laminas/laminas-eventmanager/src/EventManager.php(179): Laminas\EventManager\EventManager->triggerListeners()
#16 /srv/http/omeka-s-4.0.1/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(97): Laminas\EventManager\EventManager->triggerEventUntil()
#17 /srv/http/omeka-s-4.0.1/vendor/laminas/laminas-mvc/src/DispatchListener.php(132): Laminas\Mvc\Controller\AbstractController->dispatch()
#18 /srv/http/omeka-s-4.0.1/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\Mvc\DispatchListener->onDispatch()
#19 /srv/http/omeka-s-4.0.1/vendor/laminas/laminas-eventmanager/src/EventManager.php(179): Laminas\EventManager\EventManager->triggerListeners()
#20 /srv/http/omeka-s-4.0.1/vendor/laminas/laminas-mvc/src/Application.php(325): Laminas\EventManager\EventManager->triggerEventUntil()
#21 /srv/http/omeka-s-4.0.1/index.php(21): Laminas\Mvc\Application->run()
#22 {main} {"userId":1}

**Comment by Daniel-KM** [comment]
This feature was fixed and moved into module BlockPlus.
