### ISSUE TITLE
Error: 'omeka_2' is not defined.

### ISSUE THREAD

**Issue by pprw** [Daniel-KM/Omeka-S-module-Next#4]
We have the following error when searching a itemfrom the admin interface. It seems to be related to the presence of accented character in the search. The error go away if Next is disabled. 
```

Doctrine\ORM\Query\QueryException
[Semantical Error] line 0, col 266 near 'omeka_2 DESC,': Error: 'omeka_2' is not defined.
```

**Comment by Daniel-KM** [comment]
What is your version of Omeka S and Next?

**Comment by pprw** [comment]
Omeka S 2.0.2 with Next 3.1.2.23 both recently updated

**Comment by Daniel-KM** [comment]
It should be fixed in 3.1.2.24.

**Comment by Daniel-KM** [comment]
Else, i need the full log (to get the line where next is called).

**Comment by pprw** [comment]
Thanks!

Here is the full log trace:

```
 Doctrine\ORM\Query\QueryException
[Semantical Error] line 0, col 260 near 'omeka_2 DESC,': Error: 'omeka_2' is not defined.

Détails :

Doctrine\ORM\Query\QueryException: SELECT omeka_root.id FROM Omeka\Entity\Item omeka_root INNER JOIN Omeka\Entity\FulltextSearch omeka_1 WITH omeka_1.id = omeka_root.id AND omeka_1.resource = 'items' WHERE MATCH(omeka_1.title, omeka_1.text) AGAINST ('rinck') > 0 GROUP BY omeka_root.id ORDER BY omeka_2 DESC, omeka_root.created DESC, omeka_root.id DESC in /home/pierre/sites_web/local/hp_local/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:43
Stack trace:
#0 /home/pierre/sites_web/local/hp_local/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(491): Doctrine\ORM\Query\QueryException::dqlError('SELECT omeka_ro...')
#1 /home/pierre/sites_web/local/hp_local/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(715): Doctrine\ORM\Query\Parser->semanticalError('line 0, col 260...', Array)
#2 /home/pierre/sites_web/local/hp_local/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(275): Doctrine\ORM\Query\Parser->processDeferredResultVariables()
#3 /home/pierre/sites_web/local/hp_local/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(359): Doctrine\ORM\Query\Parser->getAST()
#4 /home/pierre/sites_web/local/hp_local/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php(283): Doctrine\ORM\Query\Parser->parse()
#5 /home/pierre/sites_web/local/hp_local/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php(207): Doctrine\ORM\Query->_parse()
#6 /home/pierre/sites_web/local/hp_local/modules/Next/src/View/Helper/BrowsePreviousNext.php(130): Doctrine\ORM\Query->getSQL()
#7 /home/pierre/sites_web/local/hp_local/modules/Next/src/View/Helper/BrowsePreviousNext.php(67): Next\View\Helper\BrowsePreviousNext->previousNext(Object(Omeka\Api\Representation\ItemRepresentation), Array)
#8 [internal function]: Next\View\Helper\BrowsePreviousNext->__invoke(Object(Omeka\Api\Representation\ItemRepresentation))
#9 /home/pierre/sites_web/local/hp_local/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php(397): call_user_func_array(Object(Next\View\Helper\BrowsePreviousNext), Array)
#10 /home/pierre/sites_web/local/hp_local/modules/Next/view/omeka/admin/item/show.phtml(28): Zend\View\Renderer\PhpRenderer->__call('browsePreviousN...', Array)
#11 /home/pierre/sites_web/local/hp_local/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php(506): include('/home/pierre/si...')
#12 /home/pierre/sites_web/local/hp_local/vendor/zendframework/zend-view/src/View.php(207): Zend\View\Renderer\PhpRenderer->render(NULL)
#13 /home/pierre/sites_web/local/hp_local/vendor/zendframework/zend-view/src/View.php(236): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
#14 /home/pierre/sites_web/local/hp_local/vendor/zendframework/zend-view/src/View.php(200): Zend\View\View->renderChildren(Object(Zend\View\Model\ViewModel))
#15 /home/pierre/sites_web/local/hp_local/vendor/zendframework/zend-mvc/src/View/Http/DefaultRenderingStrategy.php(105): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
#16 /home/pierre/sites_web/local/hp_local/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\View\Http\DefaultRenderingStrategy->render(Object(Zend\Mvc\MvcEvent))
#17 /home/pierre/sites_web/local/hp_local/vendor/zendframework/zend-eventmanager/src/EventManager.php(171): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent))
#18 /home/pierre/sites_web/local/hp_local/vendor/zendframework/zend-mvc/src/Application.php(367): Zend\EventManager\EventManager->triggerEvent(Object(Zend\Mvc\MvcEvent))
#19 /home/pierre/sites_web/local/hp_local/vendor/zendframework/zend-mvc/src/Application.php(348): Zend\Mvc\Application->completeRequest(Object(Zend\Mvc\MvcEvent))
#20 /home/pierre/sites_web/local/hp_local/index.php(21): Zend\Mvc\Application->run()
#21 {main}

Next Doctrine\ORM\Query\QueryException: [Semantical Error] line 0, col 260 near 'omeka_2 DESC,': Error: 'omeka_2' is not defined. in /home/pierre/sites_web/local/hp_local/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:65
Stack trace:
#0 /home/pierre/sites_web/local/hp_local/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(491): Doctrine\ORM\Query\QueryException::semanticalError('line 0, col 260...', Object(Doctrine\ORM\Query\QueryException))
#1 /home/pierre/sites_web/local/hp_local/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(715): Doctrine\ORM\Query\Parser->semanticalError('line 0, col 260...', Array)
#2 /home/pierre/sites_web/local/hp_local/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(275): Doctrine\ORM\Query\Parser->processDeferredResultVariables()
#3 /home/pierre/sites_web/local/hp_local/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(359): Doctrine\ORM\Query\Parser->getAST()
#4 /home/pierre/sites_web/local/hp_local/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php(283): Doctrine\ORM\Query\Parser->parse()
#5 /home/pierre/sites_web/local/hp_local/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php(207): Doctrine\ORM\Query->_parse()
#6 /home/pierre/sites_web/local/hp_local/modules/Next/src/View/Helper/BrowsePreviousNext.php(130): Doctrine\ORM\Query->getSQL()
#7 /home/pierre/sites_web/local/hp_local/modules/Next/src/View/Helper/BrowsePreviousNext.php(67): Next\View\Helper\BrowsePreviousNext->previousNext(Object(Omeka\Api\Representation\ItemRepresentation), Array)
#8 [internal function]: Next\View\Helper\BrowsePreviousNext->__invoke(Object(Omeka\Api\Representation\ItemRepresentation))
#9 /home/pierre/sites_web/local/hp_local/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php(397): call_user_func_array(Object(Next\View\Helper\BrowsePreviousNext), Array)
#10 /home/pierre/sites_web/local/hp_local/modules/Next/view/omeka/admin/item/show.phtml(28): Zend\View\Renderer\PhpRenderer->__call('browsePreviousN...', Array)
#11 /home/pierre/sites_web/local/hp_local/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php(506): include('/home/pierre/si...')
#12 /home/pierre/sites_web/local/hp_local/vendor/zendframework/zend-view/src/View.php(207): Zend\View\Renderer\PhpRenderer->render(NULL)
#13 /home/pierre/sites_web/local/hp_local/vendor/zendframework/zend-view/src/View.php(236): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
#14 /home/pierre/sites_web/local/hp_local/vendor/zendframework/zend-view/src/View.php(200): Zend\View\View->renderChildren(Object(Zend\View\Model\ViewModel))
#15 /home/pierre/sites_web/local/hp_local/vendor/zendframework/zend-mvc/src/View/Http/DefaultRenderingStrategy.php(105): Zend\View\View->render(Object(Zend\View\Model\ViewModel))
#16 /home/pierre/sites_web/local/hp_local/vendor/zendframework/zend-eventmanager/src/EventManager.php(322): Zend\Mvc\View\Http\DefaultRenderingStrategy->render(Object(Zend\Mvc\MvcEvent))
#17 /home/pierre/sites_web/local/hp_local/vendor/zendframework/zend-eventmanager/src/EventManager.php(171): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent))
#18 /home/pierre/sites_web/local/hp_local/vendor/zendframework/zend-mvc/src/Application.php(367): Zend\EventManager\EventManager->triggerEvent(Object(Zend\Mvc\MvcEvent))
#19 /home/pierre/sites_web/local/hp_local/vendor/zendframework/zend-mvc/src/Application.php(348): Zend\Mvc\Application->completeRequest(Object(Zend\Mvc\MvcEvent))
#20 /home/pierre/sites_web/local/hp_local/index.php(21): Zend\Mvc\Application->run()
#21 {main}
```

**Comment by Daniel-KM** [comment]
It's a real issue, but hard to fix. In the meantime, you can add `return [null, null];` line 82 of the file src/View/Helper/BrowsePreviewNext.php

**Comment by Daniel-KM** [comment]
This is fixed in last version.
